---
title: "dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
    theme: cosmo
  
---

```{r setup, include=FALSE}
library(flexdashboard)

library (p8105.datasets)
library (tidyverse)
library (plotly)
```

```{r}
data("nyc_airbnb")
nyc_airbnb = 
  nyc_airbnb |> 
  mutate(rating = review_scores_location / 2) |>
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) |>
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```


Column {data-width=350}
-----------------------------------------------------------------------

### Scatterplot

```{r scatterplot}
nyc_airbnb |>
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) |> 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~rating, text=~text_label, alpha = 0.5)
```

Column {data-width=350}
-----------------------------------------------------------------------

### boxplot

```{r boxplot}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood,price )) %>% 
  plot_ly(y=~price,
          type="box",
          color=~neighbourhood,
          colors = "viridis")
```

### barcode

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x=~neighbourhood, y=~ n, color=~ neighbourhood, colors = "viridis" )
```

